<?php

/** @var PauloVictorDev\Testimonials\Block\Widget\Form $block */

if ($block->isEnabled()) :
    $widgetId = uniqid('', false);
    $title = $block->getData('title');
?>

    <div class="testimonials-widget" id="<?= $widgetId ?>">
        <form class="form testimonial"
              id="testimonial-form"
              action="<?= $block->escapeUrl($block->getFormAction()) ?>"
              method="post"
              enctype="multipart/form-data"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= __($title) ?></span></legend><br />
                    <div class="field testimonial-name required">
                        <label class="label" for="name"><span><?= __('Name') ?></span></label>
                        <div class="control">
                            <input name="name" id="name"
                                   type="text"
                                   class="input-text"
                                   title="<?= __('Name') ?>"
                                   data-validate="{required:true}"/>
                        </div>
                    </div>
                <?php if ($block->isDesignationEnabled()): ?>
                    <div class="field testimonial-designation">
                        <label class="label" for="designation"><span><?= __('Designation') ?></span></label>
                        <div class="control">
                            <input name="designation" id="designation"
                                   type="text"
                                   class="input-text"
                                   title="<?= __('Designation') ?>"
                                   data-validate="{required:false}"/>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if ($block->isCompanyEnabled()): ?>
                    <div class="field testimonial-company">
                        <label class="label" for="company"><span><?= __('Company') ?></span></label>
                        <div class="control">
                            <input name="company" id="company"
                                   type="text"
                                   class="input-text"
                                   title="<?= __('Company') ?>"
                                   data-validate="{required:false}"/>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if ($block->isEmailEnabled()): ?>
                    <div class="field testimonial-email required">
                        <label class="label" for="email"><span><?= __('Email') ?></span></label>
                        <div class="control">
                            <input name="email" id="email"
                                   type="email"
                                   class="input-text"
                                   title="<?= __('Email') ?>"
                                   data-validate="{'validate-email':true, required:true}"/>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if ($block->isPictureEnabled()): ?>
                    <div class="field testimonial-picture">
                        <label class="label" for="picture"><span><?= __('Profile picture') ?></span></label>
                        <div class="control">
                            <input name="picture" id="picture"
                                   type="file"
                                   class="input-text"
                                   title="<?= __('Profile picture') ?>"
                                   accept="image/jpg, image/jpeg, image/png"
                                   data-validate="{required:false}"/>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="field testimonial-message required">
                    <label class="label" for="message"><span><?= __('Message') ?></span></label>
                    <div class="control">
                        <textarea name="message" id="message"
                                  class="input-text"
                                  title="<?= __('Message') ?>"
                                  cols="5" rows="5"
                                  data-validate="{required:true}"></textarea>
                    </div>
                </div>
            </fieldset>

            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" title="<?= __('Submit') ?>" class="action submit primary">
                        <span><?= __('Submit') ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>

<?php endif; ?>
